### ISSUE TITLE
Huge cleanup of this repository needed

### ISSUE THREAD

**Issue by dumblob** [wf9a5m75/redis-android#1]
From https://github.com/rikiji/redis-android/issues/1#issuecomment-353510564 :

Hi @wf9a5m75, glad to hear there are some changes.

May I first propose cleaning up the repository from all compilable binary files? I.e. `*.so` `*.a` `*.o` (don't forget to gitignore them). Then I'll look closer and try to propose ways how to avoid duplication and unnecessary content. Currently it seems to me, there is a whole redis repository included several times on various places. This disallows pushing any changes back to the [main redis repository](https://github.com/antirez/redis ) and thus I would propose using subrepositories.

Also I noticed there are included more versions of redis in https://github.com/wf9a5m75/redis-android/tree/master/repository/io/wf9a5m75/redis-android which doesn't make any sense to me. IMHO just one version should be supported at a time. Other versions shall definitely be not present.

**Comment by wf9a5m75** [comment]
Some people still needs to use `*.so`, `*.a`, `*.o`.
Some other people (like you),I provide the gradle installation instruction which only installs necessary binaries, you should use the gradle installation.


The reason of I don't sent a PR is the number of pending at the main repository.

![screen shot 2017-12-29 at 9 12 24 am](https://user-images.githubusercontent.com/167831/34442660-709e54da-ec78-11e7-8cef-9f55a5acebfb.png)

The pending PR is `536`. It's kidding me. They are already out-of-control themselves.


Well, I didn't ask to use this repo mandatory. If you are not favor this repo, do your self.

**Comment by dumblob** [comment]
Hi @wf9a5m75, let me apologize for my open critique. I appreciate your effort to make Redis working on Android and publishing the work. If the binaries are necessary for someone, please document it in the README file as it's a very uncommon and non-standard practice. It makes also the repository literally huge (to clone and work with).

We also shall not forget, that these binaries are not signed by any authority and therefore they are not trustworthy enough (I don't know any company, which would take these binaries and use them - it's too dangerous).

With the PRs you're right. The number is high and Salvatore is quite strict and self-minded when it comes to technical solutions. On the other hand, it's the only place where you can get reviews for free, which will increase the quality of this solution. It simply leverages the open source principles for better outcomes in a short time.

Either way, feel free to continue with your work and enjoy!
