### ISSUE TITLE
How to close the redis server 

### ISSUE THREAD

**Issue by Akash-github-project** [wf9a5m75/redis-android#11]
I am attempting to run it in a worker thread i need to end it on application end. **how can i do that**

**Comment by wf9a5m75** [comment]
https://redis.io/commands/shutdown/

**Comment by Akash-github-project** [comment]
Thanks for quick response , but i was asking if there is way to shutdown redis using your library?

**Comment by wf9a5m75** [comment]
There is no way to shutdown from outside of the redis except killing the server process (shutdown the service).

**Comment by wf9a5m75** [comment]
If you don't want to loose any data when you stop the redis, connect to the server then run the `shutdown` command.

**Comment by Akash-github-project** [comment]
Thanks I ran it inside a service on a different thread then as soon as my app closes redis server also stops
