### ISSUE TITLE
May I ask you about how to cross-compile Redis?

### ISSUE THREAD

**Issue by KangDuoLa** [wf9a5m75/redis-android#12]
**I want to compile a higher version of redis-server to run on an Android device, but I encountered errors during compilation.** 
e.g.:
server.c:2443:5: warning: implicit declaration of function 'pthread_setcancelstate' [-Wimplicit-function-declaration]
     pthread_setcancelstate(PTHREAD_CANCEL_ENABLE, NULL);
     ^
server.c:2443:28: error: 'PTHREAD_CANCEL_ENABLE' undeclared (first use in this function)
     pthread_setcancelstate(PTHREAD_CANCEL_ENABLE, NULL);
                            ^
server.c:2443:28: note: each undeclared identifier is reported only once for each function it appears in
server.c:2444:5: warning: implicit declaration of function 'pthread_setcanceltype' [-Wimplicit-function-declaration]
     pthread_setcanceltype(PTHREAD_CANCEL_ASYNCHRONOUS, NULL);
     ^
server.c:2444:27: error: 'PTHREAD_CANCEL_ASYNCHRONOUS' undeclared (first use in this function)
     pthread_setcanceltype(PTHREAD_CANCEL_ASYNCHRONOUS, NULL);

**I would like to know how to compile and solve these errors. I am deeply grateful!!**

**Comment by wf9a5m75** [comment]
Sorry, I forgot how I did.

**Comment by KangDuoLa** [comment]
Thanks!
