### ISSUE TITLE
can you provide a APK installation package?

### ISSUE THREAD

**Issue by ithjz** [wf9a5m75/redis-android#2]
Hello, can you provide a APK installation package?

It is convenient for us to download and use.

**Comment by wf9a5m75** [comment]
nop. I don't want to spend my time to customer services from normal people.

There is an apk that is already included redis3.2.7

https://play.google.com/store/apps/details?id=io.tempage.doryredis

**Comment by ithjz** [comment]
@wf9a5m75  Thank you
