### ISSUE TITLE
Stop server 

### ISSUE THREAD

**Issue by AncientCoder** [wf9a5m75/redis-android#3]
hi I need to stop the Redis server in my ondestroy call within my service.  Is there a way to do this as it seems to be running in its own thread and not getting disposed even my service dies?

**Comment by wf9a5m75** [comment]
Server is stopped automatically when your app is destroyed.

**Comment by wf9a5m75** [comment]
>I have another issue, not related to your solution, with the client still thinking its connected even after it was destroyed

That's Redis itself's problem, not this library.
I have no knowledge inside Redis itself. I just cross-compile Redis for myself, and share it for other people.
Please ask at the Redis community.

**Comment by AncientCoder** [comment]
Yes agree that's why I said not related to your solution.  Anyway please keep sharing :-)

**Comment by dpnkrg** [comment]
> Server is stopped automatically when your app is destroyed.

I want to still connected to Redis-server when the app is destroyed in the background.
