### ISSUE TITLE
pre-built redis-server

### ISSUE THREAD

**Issue by molinjun** [wf9a5m75/redis-android#6]
Hi @wf9a5m75 , the redis-android is an awesome idea to cross built redis. but it just offer the redis-cli in prebuilt zip file. Do you have a plan to offer the redis-server? Thanks for your answer.

**Comment by wf9a5m75** [comment]
Installation.
https://github.com/wf9a5m75/redis-android#install

Then you can run redis-server in your app.

**Comment by molinjun** [comment]
@wf9a5m75 Thx for your answer, Massahi, I have noticed that. But I mean that could u like to add a redis-server prebuilt into the zip.

**Comment by molinjun** [comment]
@wf9a5m75 Thx for your answer, Massahi, I have noticed that. But I mean that could u like to add a redis-server prebuilt into the zip.

**Comment by wf9a5m75** [comment]
Pre-build server binary files are not necessary for other people.
In that case, please build them by yourself using Android NDK.
That's why code is full open source.

**Comment by molinjun** [comment]
Thanks， I will close the issue.

**Comment by jelly-FF** [comment]
@gedennis 
Hi, have you successfully built the redis-server prebuilt?
