### ISSUE TITLE
Could Redis-Android supports RadisGraph?

### ISSUE THREAD

**Issue by zhuguocheng29** [wf9a5m75/redis-android#7]
I want to use RedisGraph on Android based on Redis. Official document says that Redis load RedisGraph during startup by adding the following to redis.conf file:
loadmodule /path/to/module/src/redisgraph.so

Could redis-android supports add .so file or uses other methods?

**Comment by wf9a5m75** [comment]
Um, I've never tried it.

**Comment by gkorland** [comment]
@zhuguocheng29 did you manage to run the module on android?

**Comment by zhuguocheng29** [comment]
@gkorland No, it doesn't work
