### ISSUE TITLE
redis-android

### ISSUE THREAD

**Issue by smxy34** [wf9a5m75/redis-android#8]
问题:
1、设备是否一定需要有root权限，没有root权限，手动操作呢？
2、输入指令 redis-cli 出现
WARNING: linker: redis-cli: unused DT entry: type 0x6ffffffe arg 0x1248
WARNING: linker: redis-cli: unused DT entry: type 0x6fffffff arg 0x3
?[6n （设备是Android5.1.1 具备root权限）
3、APP安装到安卓设备上，没有响应，需要配置redis 服务器的ip地址？

**Comment by smxy34** [comment]
question：
1、My devices must need ROOT permission?
2、when I input redis-cli commond,it tips:
WARNING: linker: redis-cli: unused DT entry: type 0x6ffffffe arg 0x1248
WARNING: linker: redis-cli: unused DT entry: type 0x6fffffff arg 0x3
?[6n （devices is Android5.1.1 and  get root permission）
3、when install redis-android.apk into device,No response，may I do something?

thank you very much!

**Comment by wf9a5m75** [comment]
> 1、My devices must need ROOT permission?

Not necessary if you use just database service.

> 2、when I input redis-cli commond

For some reasons, redis-cli does not work on some devices.
The `redis-cli` of old-versions work some times.
https://github.com/wf9a5m75/redis-android/releases

> 3、when install redis-android.apk into device,No response，may I do something?

Please check out the logcat.
Source code is open.
https://github.com/wf9a5m75/redis-android/tree/master/app

**Comment by smxy34** [comment]
If your device haven't ROOT permission,thest commond are error.
![image](https://user-images.githubusercontent.com/5261021/63935684-92e39300-ca90-11e9-9217-09bde50d64ca.png)
![image](https://user-images.githubusercontent.com/5261021/63935779-c6beb880-ca90-11e9-8f6a-ac3b4f407d54.png)
Redis supports setting values to Redis servers on Android devices？
Thank you!

**Comment by wf9a5m75** [comment]
If you don't have root permission, you can't install redis-cli.

But redis-cli is not necessary element.
The pre-build redis-cli is only for debug.

You can still connect to the redis db from your computer with normal redis-cli or applications.
https://fastoredis.com/

**Comment by smxy34** [comment]
When running the program redis-android, here is the Log information：
![image](https://user-images.githubusercontent.com/5261021/63986211-8fd6ba00-cb05-11e9-8c09-1bd5073aa2e8.png)
Redis start on port 6379, What It delegate visit redis DB connected successfully?
int rc = native_redisStart(redisConfig);This method call does not respond,
Other question, Can I user redis-android Application set key-value to redis DB?
Thank you very much！

**Comment by wf9a5m75** [comment]
Please use `RedisAndroid.start` instead of `int rc = native_redisStart(redisConfig);`
https://github.com/wf9a5m75/redis-android/blob/master/app/src/main/java/example/redis/android/wf9a5m75/exampleapp/RedisService.java

`native_redisStart` does not return until the server is end.

**Comment by wf9a5m75** [comment]
Once redis DB runs on Android (after `RedisAndroid.start`), you can set key-value data into the redis DB.

However this library does not provide redis client.
You need to use another redis client library to connect to the DB.

**Comment by smxy34** [comment]
OK,thank you!
You are a good man.

**Comment by smxy34** [comment]
First, my requirement is that redis DB runs on windows and redis-cli runs on Android devices, setting values directly from Android devices to redis db. Is this solution feasible?

**Comment by wf9a5m75** [comment]
In that case, this library is not for you.
This library is designed for `running redis DB on Android` and `connecting from windows`.

**Comment by smxy34** [comment]
what about https://fastoredis.com/registered_users_downloads
It supports Android
![image](https://user-images.githubusercontent.com/5261021/63987779-01196b80-cb0c-11e9-9642-79b1e5dc6c65.png)
Can meet my needs?

**Comment by wf9a5m75** [comment]
I'm not your free Q&A service. I only answer for the questions of this library.
